server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/print
    username: root
    password: doanh@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  siginer-key: "aP+kMERx9Si8IXoraYLGCdVU1TuDMK31AgH4YlSayqW5c4Ly74TUs/5V1spu90Kh"